# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53413c8f0fa27e7fed9d5399b074700c2f038322030f607c400c3a745bb864bbc0f10d93ad9f2a5684a29ec864f0be33939507d2ef01750d7bbdbc3e8bc77328

test:
  secret_key_base: 6972c85d27a33e7eb4b4d99850f4dcb1085a130181d1ccde11cb443868dac8d308936aac8fe20f4a8a1ac13e365731aaf9192769e7c9ce4e675b80a1f8bc684e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
